### ISSUE TITLE
python version only configurable via PATH

### ISSUE THREAD

**Issue by gwu** [jmendiara/node-closure-linter-wrapper#17]
It would be nice to be able to specify an explicit path for python rather than relying on the PATH environment variable.

I'm running into an issue where this is being called from an environment where the python found in PATH is python 3, which is not yet compatible with gjslint. See https://code.google.com/p/closure-linter/issues/detail?id=81.

**Comment by gwu** [comment]
I believe I have a pull request #18 that will address both this issue and #13

**Comment by yisding** [comment]
Would it be possible to specify a path to gjslint itself as well? I ask because the version of gjslint in this package is out of date by a few revisions.

**Comment by jmendiara** [comment]
@yisding you can send a PR with the updated gjslint as well ;)

**Comment by jmendiara** [comment]
@yisding I've updated the bundled `closure-linter` to v2.3.17 in the release v1.0.0

**Comment by yisding** [comment]
Thanks Javier!
